# Generated by Django 3.2.5 on 2026-01-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
